---

- name: Install Node.js & NPM
  become: yes
  become_user: root
  apt: name="{{ item }}" state=latest
  with_items:
    - nodejs
    - npm

- name: Install NPM Libraries
  become: yes
  become_user: root
  npm: name="{{ item }}" state=latest global=yes
  with_items:
    - bower
    - grunt-cli
