---

- name: Creates a GeoNode development virtual machine
  hosts: all
  remote_user: vagrant

  roles:
    #- common_networking_centos  # Configure iptables for outside access
    - common_base_ubuntu  # Installs basic libraries, including GCC, PIP
    - common_java_ubuntu # Installs Java
    #- common_db_centos  # Installs gdal & postgres, builds PostGIS from source, and creates template_postgis
    #- common_memcached_centos
    #- common_rabbitmq_centos  # Required by celery, which is used by GeoNode
    #- common_webserver_tomcat_centos  # Installs Tomcat and Configures Service
    - common_webserver_django_ubuntu  # Installs dependencies, and configures uwsgi service
    - common_webserver_proxy_ubuntu  # Installs NGINX, and configures service
    - common_venv_ubuntu
    - geonode
